config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'user/registrations' }

  resources :user_stocks, except: [:index, :show, :edit, :update]

  resources :users, only: [:show]

  resources :friendships

  root 'welcome#index'

  get  'search_stocks',  to: 'stocks#search'
  get  'update_stocks',  to: 'stocks#update_stocks_prices'
  get  'my_portfolio',   to: 'users#my_portfolio'
  get  'my_friends',     to: 'users#my_friends'
  get  'search_friends', to: "users#search"
  post 'add_friend',     to: "users#add_friend"

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.find_by_ticker(ticker_symbol)
    find_by(ticker: ticker_symbol)
  end

  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)

    return nil unless looked_up_stock.name

    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    new_stock.last_price = new_stock.price
    new_stock
  end

  def price
    stock = StockQuote::Stock.quote(ticker)

    if stock.response_code == 200
      closing_price = stock.close
      return "#{closing_price} (Closing)" if closing_price

      opening_price = stock.open
      return "#{opening_price} (Opening)" if opening_price
    else
      'Unavailable'
    end
  end

  def update_time
    updated_at.in_time_zone.strftime("%B %e, %Y at %l:%M%P %Z")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    'Anonymous User'
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).empty?
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def self.search(param)
    return User.none if param.blank?

    param.strip!
    param.downcase!
    (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("lower(#{field_name}) like ?", "%#{param}%")
  end
end

app/models/user_stock.rb
class UserStock < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship = current_user.friendships.find_by(friend_id: params[:id])

    if @friendship.destroy
      flash[:notice] = 'Friend was successfully removed.'
      redirect_to :back
    else
      flash[:error] = 'Something went wrong while removing Friend'
      redirect_to :back
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock   = Stock.find_by_ticker(params[:stock].upcase)
      @stock ||= Stock.new_from_lookup(params[:stock])
    end

    if @stock
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
  end

  def update_stocks_prices
    @user        = current_user
    @user_stocks = @user.stocks

    @user_stocks.each { |stock| stock.update(last_price: stock.price) }

    render partial: 'stocks/list'
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    @user_stock =
      if params[:stock_id].present?
        UserStock.new(user: current_user, stock_id: params[:stock_id])
      else
        stock = create_stock
        UserStock.new(user: current_user, stock: stock)
      end

    if @user_stock.save
      flash[:notice] = "Stock #{@user_stock.stock.ticker} was successfully added"
      redirect_to my_portfolio_path
    else
      flash[:alert] = "Something went wrong. #{@user_stock.errors.inspect}"
      redirect_to my_portfolio_path
    end
  end

  def destroy
    @user_stock = UserStock.find_by(stock_id: params[:id])

    if @user_stock.destroy
      flash[:notice] = 'Stock was successfully removed from portfolio.'
      redirect_to my_portfolio_path
    else
      flash[:alert] = 'Unable to remove stock from portfolio.'
      redirect_to my_portfolio_path
    end
  end

  private

  def user_stock_params
    params.require(:user_stock).permit(:user_id, :stock_id)
  end

  def create_stock
    Stock.create(
      ticker: params[:stock_ticker],
      name: params[:stock_name],
      last_price: BigDecimal.new(params[:stock_price])
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user        = User.find(params[:id])
    @user_stocks = @user.stocks
  end

  def my_portfolio
    @user_stocks = current_user.stocks
    @user        = current_user
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    @users = User.search(params[:search_param])

    if @users
      @users = current_user.except_current_user(@users)
      render partial: 'friends/lookup'
    else
      render status: :not_found, nothing: true
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      flash[:notice] = 'Friend was successfully added'
      redirect_to my_friends_path
    else
      flash[:error] = "There was an error adding #{@friend.full_name} as friend"
      redirect_to my_friends_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/common/_big_spinner.html.erb
<div id='big-spinner' class='row col-md-12 text-center'>
  <i class='fa fa-cog fa-spin fa-5x'></i>
  <h3>Updating...</h3>
</div>

app/views/common/_spinner.html.erb
<div id='spinner' class='row col-md-12 text-center' style='display: none;'>
  <i class='fa fa-spinner fa-spin fa-2x'></i> Processing...
  <br>
  <br>
</div>

app/views/friends/_lookup.html.erb
<div id='friend-lookup'>
  <h3>Search for friends</h3>

  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
    <div class='form-group row no-padding text-center col-md-12'>
      <div class='col-md-10'>
        <%= text_field_tag :search_param,
            params[:search_param],
            placeholder: 'first name, last name or email',
            autofocus: true,
            class: 'form-control search-box input-md' %>
      </div>
      <div class='col-md-2'>
        <%= button_tag(type: :submit, class: 'btn btn-md btn-success') do %>
          <i class='fa fa-search'></i> Look up a friend
        <% end %>
      </div>
    </div>
  <% end %>

  <%= render 'common/spinner' %>

  <% if @users %>
    <% if @users.size > 0 %>
      <div id='friend-lookup-results' class='well results-block'>
        <table class='search-results-table col-md-12'>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><strong>Name:</strong> <%= user.full_name %></td>
                <td><strong>Email:</strong> <%= user.email %></td>
                <td><strong>Profile:</strong> <%= link_to 'View Profile', user_path(user),
                                                          class: 'btn btn-xs btn-success' %>
                  <% if current_user.not_friends_with?(user.id) %>
                    <%= link_to 'Add as my friend',
                        add_friend_path(user: current_user, friend: user),
                        class: 'btn btn-xs btn-success',
                        method: :post %>
                  <% else %>
                    <span class='label label-primary'>
                      You are friends
                    </span>
                  <% end %>
                </td>
              </tr><!-- end of <tr> inside loop -->
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p class='lead col-md-12'>
        No people match this search criteria
      </p>
    <% end %>
  <% end %>
  <div id='friend-lookup-errors'></div>
</div>

app/views/layouts/_navbar.html.erb
<div class='navbar navbar-default navbar-static-top'>
  <div class='container'>
    <%= link_to 'Financify', root_path, class: 'navbar-brand' %>
    <% if current_user %>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-responsive-collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <div class='navbar-collapse collapse navbar-responsive-collapse'>
        <ul class='nav navbar-nav col-md-6'>
          <li><%= link_to 'My Portfolio', my_portfolio_path %></li>
          <li><%= link_to 'My Friends', my_friends_path  %></li>
          <li><%= link_to 'My Profile', edit_registration_path(current_user) %></li>
        </ul>
        <ul class='nav navbar-right col-md-4'>
          <li class='col-md-8 user-name text-right'>
            <i class='fa fa-user'></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class='col-md-4 logout'>
            <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Financify" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_list.html.erb
<%= render 'common/big_spinner' %>

<table id='stock-portfolio' class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
      <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.name %></td>
        <td><%= user_stock.ticker %></td>
        <td><%= user_stock.last_price %></td>
        <% if @user.id == current_user.id %>
          <td>
            <%= link_to 'Delete',
                user_stock_path(user_stock),
                method: :delete,
                data:   { confirm: 'Are you sure?' },
                class: 'btn btn-xs btn-danger' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/_lookup.html.erb
<div id='stock-lookup'>
  <h3>Search for Stocks</h3>

  <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
    <div class='form-group row no-padding text-center col-md-12'>
      <div class='col-md-10'>
        <%= text_field_tag :stock,
            params[:stock],
            placeholder: 'Stock ticker symbol',
            autofocus: true,
            required: true,
            class: 'form-control search-box input-md' %>
      </div>
      <div class='col-md-2'>
        <%= button_tag(type: :submit, class: 'btn btn-md btn-success') do %>
          <i class='fa fa-search'></i>
          Look up a stock
        <% end %>
      </div>
    </div>
  <% end %>

  <%= render 'common/spinner' %>

  <% if @stock %>
    <div id='stock-lookup-results' class='well results-block'>
      <strong>Symbol:</strong> <%= @stock.ticker %>
      <strong>Name:</strong> <%= @stock.name %>
      <strong>Price:</strong> <%= @stock.price %>
      <% if current_user.can_add_stock?(@stock.ticker) %>
        <%= link_to 'Add to my Stocks',
            user_stocks_path(
              user: current_user,
              stock_ticker: @stock.ticker,
              stock_name: @stock.name,
              stock_price: @stock.last_price,
              stock_id: @stock.id? ? @stock.id : ''),
            class: 'btn btn-xs btn-success',
            method: :post %>
      <% else %>
        <br/>
        <span class='label label-warning'>
          Stock cannot be added because you have already added
          <% if !current_user.under_stock_limit? %>
            10 stocks
          <% end %>
          <% if current_user.stock_already_added?(@stock.ticker) %>
            this stock
          <% end %>
        </span>
      <% end %>
    </div>
  <% end %>

  <div id='stock-lookup-errors'></div>
</div>

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>

<% if @friendships.size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="3" class="page-header">
          <h2>My Friends</h2>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
      <tr>
        <td><%= friend.full_name %></td>
        <td><%= friend.email %></td>
        <td>
          <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
          <%= link_to 'Remove Friend',
              friendship_path(friend),
              method: :delete,
              data: { confirm: "Are you sure?" },
              class: "btn btn-xs btn-danger" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="row col-lg-12">
    <p class="lead">You don't have any friends yet. Please add some!</p>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<%= render 'stocks/lookup' %>
<%= render 'stocks/list' %>

<%= link_to 'Update Stock Prices',
    update_stocks_path,
    remote: :true,
    id: 'update-stocks-button',
    class:  'btn btn-md btn-info' %>

<br>
<br>
<div id='last-updated'>
  <strong>Stocks Last Updated: </strong>
  <em><%= @user_stocks.first.update_time %></em>
</div>
<hr>

app/views/users/show.html.erb
<h2>User Details</h2>

<dl class='dl-horizontal'>
  <dt><strong>Full Name</strong></dt>
  <dd><%= @user.full_name %></dd>
  <dt><strong>Email</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<% if @user.stocks.size > 0 %>
  <%= render 'stocks/list' %>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %>

<%= link_to 'Back', my_friends_path, class: 'btn btn-primary' %>

app/views/welcome/index.html.erb
<h1>Financify</h1>